-- Admin account is created after db reset via migrate seeds.
-- Set these env vars on Railway before first deploy / after reset:
--   ADMIN_SEED_EMAIL=your@email.com
--   ADMIN_SEED_PASSWORD=your-secure-password
--
-- Or run: npm run admin:seed (after setting env vars)
